#   _____ _____ ____  _____ _____ _____ _____    _____ _____ _____ __    __       _____ _____
#  | __  |   __|    \| __  |     |     |     |  |   __|_   _|     |  |  |  |     |     |   | |
#  | __ -|   __|  |  |    -|  |  |  |  | | | |  |__   | | | |-   -|  |__|  |__   |  |  | | | |
#  |_____|_____|____/|__|__|_____|_____|_|_|_|  |_____| |_| |_____|_____|_____|  |_____|_|___|
###########################################################################################
# BEDROOM CONTROL LIGHTS BASED ON STATUS SENSOR OFF 5MIN
###########################################################################################
- alias: "Control - Light - Bedroom Lights Are On"
  trigger:
    - platform: state
      entity_id: binary_sensor.zwave2mqtt_nodeid_106_contact
      to: "off"
      for: "00:10:00"

  condition:
    - condition: state
      entity_id: switch.scene_goodnight
      state: "off"

    - condition: state
      entity_id: switch.bedroom
      state: "on"

  action:
    - service: switch.turn_off
      entity_id: switch.bedroom

    - service: notify.mobile_app_peter_iphone
      data:
        message: "Nobody in bedroom for 10 minutes. Turned off bedroom switch and light"
        title: "HA System"
        data:
          push:
            thread-id: "Control System"
