#   _____ _____ ____  _____    __    _____ _____ _____ _____    _____ _____ _____ _____ _____ _____ __
#  |  |  |     |    \|     |  |  |  |     |   __|  |  |_   _|  |     |     |   | |_   _| __  |     |  |
#  |    -|  |  |  |  |-   -|  |  |__|-   -|  |  |     | | |    |   --|  |  | | | | | | |    -|  |  |  |__
#  |__|__|_____|____/|_____|  |_____|_____|_____|__|__| |_|    |_____|_____|_|___| |_| |__|__|_____|_____|
###########################################################################################
# KODI CONTROL LIGHTS RUN SCRIPT BASED ON STATUS
###########################################################################################
- alias: "Control - Light - Kodi"
  trigger:
    - platform: state
      entity_id: media_player.android

  variables:
    door_sensor_diningroom: binary_sensor.neo_diningroomdoor_custom_sensor
    motion_toilet: binary_sensor.zwave2mqtt_nodeid_87_contact
    cooking: switch.cooking

  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"

    - condition: state
      entity_id: 
        - switch.scene_goodnight
        - switch.full_manual_mode
      state: "off"

    - condition: state
      entity_id: switch.scene_kodi
      state: "on"

  action:
    - choose:
###########################################################################################
#  KODI is on play modus
###########################################################################################
        - conditions:
            - condition: state
              entity_id: media_player.android
              state: "playing"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.livingroom_all
                brightness_pct: 70

            - service: light.turn_on
              data:
                entity_id:
                  - light.window_all
                  - light.nanoleaf
                  - light.balcony_all
                brightness_pct: 30

            - service: light.turn_off
              entity_id:
                - light.newkaku_011fad02_c
                - light.newkaku_01401eb6_a

            - service: light.turn_on
              data:
                entity_id: light.dressoir_all
                brightness_pct: "{{ 0 if is_state(door_sensor_diningroom, 'on') else 25 }}"

            - service: light.turn_on
              data:
                entity_id:
                  - light.kitchen_all
                  - light.sink_all
                brightness_pct: "{{ 100 if is_state(cooking, 'on') else 0 }}"

            - service: light.turn_on
              data:
                entity_id: light.toilet_all
                brightness_pct: "{{ 100 if is_state(motion_toilet, 'on') else 0 }}"

###########################################################################################
#  KODI is on paused modus
###########################################################################################
        - conditions:
            - condition: state
              entity_id: media_player.android
              state: "paused"
          sequence:
            - service: light.turn_on
              data:
                entity_id:
                  - light.wall_all
                  - light.window_all
                  - light.kitchen_all
                  - light.sink_all
                  - light.toilet_all
                  - light.balcony_all
                brightness_pct: 100

            - service: light.turn_on
              data:
                entity_id:
                  - light.nanoleaf
                  - light.newkaku_01401eb6_a
                brightness_pct: 50

            - service: light.turn_on
              data:
                entity_id: light.dressoir_all
                brightness_pct: "{{ 0 if is_state(door_sensor_diningroom, 'on') else 100 }}"

###########################################################################################
#  KODI is on idle modus
###########################################################################################
      default:
        - service: light.turn_on
          data:
            entity_id:
              - light.wall_all
              - light.window_all
              - light.balcony_all
            brightness_pct: 100

        - service: light.turn_on
          data:
            entity_id:
              - light.nanoleaf
              - light.newkaku_01401eb6_a
            brightness_pct: 50

        - service: light.turn_on
          data:
            entity_id: light.dressoir_all
            brightness_pct: "{{ 0 if is_state(door_sensor_diningroom, 'on') else 100 }}"

        - service: light.turn_on
          data:
            entity_id:
              - light.kitchen_all
              - light.sink_all
            brightness_pct: "{{ 100 if is_state(cooking, 'on') else 0 }}"

        - service: light.turn_on
          data:
            entity_id: light.toilet_all
            brightness_pct: "{{ 100 if is_state(motion_toilet, 'on') else 0 }}"
