#   ██████╗ █████╗ ██╗     ██████╗  █████╗ ██╗   ██╗
#  ██╔════╝██╔══██╗██║     ██╔══██╗██╔══██╗██║   ██║
#  ██║     ███████║██║     ██║  ██║███████║██║   ██║
#  ██║     ██╔══██║██║     ██║  ██║██╔══██║╚██╗ ██╔╝
#  ╚██████╗██║  ██║███████╗██████╔╝██║  ██║ ╚████╔╝ 
#   ╚═════╝╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝  ╚═╝  ╚═══╝  
###########################################################################################
# Calendar import from iCloud
###########################################################################################
- platform: caldav
  username: !secret icloud_peter_username
  password: !secret icloud_app_specific_password_caldav
  url: https://caldav.icloud.com
  calendars:
    - "Funko Pops"
    - "Peter Oudenes"