#  ███████╗██╗    ██╗██╗████████╗ ██████╗██╗  ██╗███████╗███████╗
#  ██╔════╝██║    ██║██║╚══██╔══╝██╔════╝██║  ██║██╔════╝██╔════╝
#  ███████╗██║ █╗ ██║██║   ██║   ██║     ███████║█████╗  ███████╗
#  ╚════██║██║███╗██║██║   ██║   ██║     ██╔══██║██╔══╝  ╚════██║
#  ███████║╚███╔███╔╝██║   ██║   ╚██████╗██║  ██║███████╗███████║
#  ╚══════╝ ╚══╝╚══╝ ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚══════╝╚══════╝
###########################################################################################
---
###########################################################################################
# RFLINK SWITCH
# https://www.home-assistant.io/integrations/switch.rflink/
###########################################################################################

###########################################################################################
# GROUP
###########################################################################################
- platform: group
  name: "helpers_switches"
  entities:
    - switch.ceiling_light_switch
    - switch.sink_light_switch
    - switch.bedroom_light_switch
    - switch.bathroom_light_switch
    - switch.hallway_light_switch
    - switch.cooking_light_switch
    - switch.dressoir_light_switch
    - switch.diningtable_light_switch
    - switch.wall_light_switch
    - switch.window_light_switch
    - switch.balcony_light_switch
    - switch.toilet_light_switch

- platform: group
  name: "helpers_zwave_wallswitches"
  entities:
    - switch.xmas_tree_wall
    - switch.imac_wall
    - switch.toog_wall
    - switch.kay_wall
    - switch.peter_wall
    - switch.balcony_wall
    - switch.bedroom_wall
    - switch.xmas_1_wall
    - switch.airfryer_wall