#   _____ _____ _____ _____    _____ _ _ _ _____ _____ _____ _____    _____ _____ _____ _____ _____ _____ _____
#  |     |   __|   __|  |  |  |   __| | | |     |_   _|     |  |  |  |     |     |     |  |  |     |   | |   __|
#  | | | |   __|   __|    -|  |__   | | | |-   -| | | |   --|     |  |   --|  |  |  |  |    -|-   -| | | |  |  |
#  |_|_|_|_____|_____|__|__|  |_____|_____|_____| |_| |_____|__|__|  |_____|_____|_____|__|__|_____|_|___|_____|
###########################################################################################
# SWITCH CONTROL FOR COOKING
###########################################################################################
- alias: "Switch - Meek Cooking"
  trigger:
    - platform: state
      entity_id: switch.cooking

  action:
    - service: "{{ 'light.turn_on' if is_state('switch.cooking', 'on') else 'light.turn_off' }}"
      entity_id: light.newkaku_011fad02_c # OLD KAKU DIMMER
