#   _____ _____ _____    _____ _____ _____ _____ _____ _____ _____ _____ _____ _____
#  |   __|  |  | __  |  | __  | __  |     |   __|  |  |_   _|   | |   __|   __|   __|
#  |   __|    -| __ -|  | __ -|    -|-   -|  |  |     | | | | | | |   __|__   |__   |
#  |__|  |__|__|_____|  |_____|__|__|_____|_____|__|__| |_| |_|___|_____|_____|_____|
###########################################################################################
# SYSTEM FKB CHANGE BRIGHTNESS
###########################################################################################
- alias: "System - FKB Change Brightness"
  trigger:
    - platform: state
      entity_id: input_number.fullykiosk_brightness_slider

  action:
    - service: shell_command.fullykiosk_brightness_slider
