#   _____ _____ _____ _____ _____    _____ _____ _____ _____ _____ _____
#  |_   _|  |  |   __|     |   __|  |     |  |  |  _  |   | |   __|   __|
#    | | |     |   __| | | |   __|  |   --|     |     | | | |  |  |   __|
#    |_| |__|__|_____|_|_|_|_____|  |_____|__|__|__|__|_|___|_____|_____|
###########################################################################################
# SYSTEM CHANGE THEME BASED ON SUN IS BELOW OR ABOVE HORIZON
###########################################################################################
- alias: "System - Automatic Theme Change Day/Night"
  trigger:
    - platform: homeassistant
      event: start

    - platform: state
      entity_id: sun.sun
      to: "below_horizon"

    - platform: state
      entity_id: sun.sun
      to: "above_horizon"

  action:
    - service: frontend.set_theme
      data:
        name: "{{ 'iOS Light Mode' if is_state('sun.sun', 'above_horizon') else 'iOS Dark Mode' }}"
