#
#   ____          _               _               _
#  |    \ ___ _ _|_|___ ___      | |_ ___ ___ ___| |_ ___ ___
#  |  |  | -_| | | |  _| -_|     |  _|  _| .'|  _| '_| -_|  _|
#  |____/|___|\_/|_|___|___|_____|_| |_| |__,|___|_,_|___|_|
#                          |_____|
###########################################################################################
# ICLOUD3
# https://github.com/gcobb321/icloud3
###########################################################################################
---
- platform: icloud3
  username: !secret icloud_peter_username
  password: !secret icloud_password
  config_ic3_file_name: "/config/package/config_ic3.yaml"
