#
#   _____ _____ _____
#  |_   _|_   _|   __|
#    | |   | | |__   |
#    |_|   |_| |_____|
#
###########################################################################################
# GOOGLE TTS
# https://www.home-assistant.io/integrations/google_translate/
###########################################################################################
---
- platform: google_translate
