#
#   _ _ _         _   _
#  | | | |___ ___| |_| |_ ___ ___
#  | | | | -_| .'|  _|   | -_|  _|
#  |_____|___|__,|_| |_|_|___|_|
#
###########################################################################################
# BUIENRADAR
# https://www.home-assistant.io/integrations/sensor.buienradar/
###########################################################################################
---
- platform: buienradar
  name: "buienradar"
