alias: AppleTV Integration - Reload every 10s
description: ""
triggers:
  - trigger: time_pattern
    seconds: "10"

conditions: []

actions:
  - action: homeassistant.reload_config_entry
    data: {}
    target:
      device_id: 0c556bea5069f2816690276667aedb6e

mode: single