#   _____ _____ _____ _____ _____ _____    _____ _____ _____ __    _____ _____
#  |     |     |_   _|     |     |   | |  |_   _|     |     |  |  |   __|_   _|
#  | | | |  |  | | | |-   -|  |  | | | |    | | |  |  |-   -|  |__|   __| | |
#  |_|_|_|_____| |_| |_____|_____|_|___|    |_| |_____|_____|_____|_____| |_|
###########################################################################################
# CONTROL LIGHT TOILET WHEN GOODNIGHT SCENE IS ACTIVE
###########################################################################################
- alias: "Motion Detection - Toilet On Off"
  mode: restart
  trigger:
    - platform: state
      entity_id: binary_sensor.zwave2mqtt_nodeid_87_contact

  variables:
    goodnight: switch.scene_goodnight
    motion_toilet: binary_sensor.zwave2mqtt_nodeid_87_contact
    adaptive: "{{ states('sensor.adaptive_lighting_color_temperature') }}"

  condition: "{{ is_state('switch.toilet', 'off') }}"

  action:
    - service: light.turn_on
      data:
        entity_id: light.toilet_all
        brightness_pct: >-
          {% if is_state(goodnight, 'on') and is_state(motion_toilet, 'on') %} 50
          {% elif is_state(goodnight, 'off') and is_state(motion_toilet, 'on') %} 100
          {% else %} 0
          {% endif %}
        kelvin: "{{ adaptive }}"

    - service: mqtt.publish
      data:
        topic: "homeassistant/ha_motion/toilet"
        payload: "{{ 1 if is_state(motion_toilet, 'on') else 0 }}"
