#########################################################
# Below all fixed settings for doorbell PCB
#########################################################
substitutions:
  devicename: meek-doorbell
  friendly: Doorbell
  ip: 192.168.100.211
  neopixel: GPIO02 # (D4)
  gpio_relay4: GPIO13 # (D7)

#########################################################
# Everything below can be copy/paste without problem
#########################################################
packages:
  wifi: !include defaults/wifi.yaml
  # device_base: !include defaults/for_all_devices.yaml

esphome:
  name: ${devicename}
  on_boot:
    priority: 600
    then:
      - lambda: WiFi.setPhyMode(WIFI_PHY_MODE_11G); 
  
# WIFI_PHY_MODE_11B: 802.11b mode, WIFI_PHY_MODE_11G: 802.11g mode, WIFI_PHY_MODE_11N: 802.11n mode

esp8266:
  board: esp01_1m
  restore_from_flash: true

api:
  encryption:
    key: !secret api_key
  reboot_timeout: 15min

time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

web_server:
  port: 80
  
preferences:
  flash_write_interval: 1min
  
logger:
  level: INFO
  
ota:
  safe_mode: true
  password: !secret password
  reboot_timeout: 0s

button:
  - platform: factory_reset
    name: "${friendly} - Reset"

switch:
  - platform: safe_mode
    name: "${friendly} - safe mode"
    id: "${friendly}_safe_mode"
    
sensor:
  - platform: wifi_signal
    name: "${friendly} - Wifi Signal"
    update_interval: 5min

  - platform: uptime
    name: "${friendly} - Uptime"
    update_interval: 5min

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly} - IP"
      icon: mdi:lan
    ssid:
      name: "${friendly} - SSID"
      icon: mdi:lan
    bssid:
      name: "${friendly} - BSSID"
      icon: mdi:lan
    mac_address:
      name: "${friendly} - MAC"
      icon: mdi:lan

  - platform: version
    name: "${friendly} - Version"
    hide_timestamp: true

light:
  - platform: neopixelbus
    default_transition_length: 0s
    type: GRB
    variant: 800KBPS
    pin: ${neopixel}
    num_leds: 1
    name: "${friendly} - Neopixel"
    restore_mode: RESTORE_DEFAULT_OFF
    id: neopixel

binary_sensor:
  - platform: gpio
    pin:
      number: ${gpio_relay4}
      inverted: true
    name: "${friendly} - Doorbell"