#########################################################
# Below all fixed settings for bedroom PCB
#########################################################
substitutions:
  devicename: meek-bedroom
  friendly: Bedroom
  ip: 192.168.100.203
  touch_power: GPIO16 # (D0)
  neopixel: GPIO02 #(D4)
  gpio_touch1: GPIO12 # (D6)
  gpio_relay1: GPIO05 # (D1)

#########################################################
# Everything below can be copy/paste without problem
#########################################################
packages:
  wifi: !include include/wifi.yaml
  device_base: !include include/device_base.yaml

light: !include include/light_one.yaml
switch: !include include/switch_one.yaml
binary_sensor: !include include/binary_sensor_one.yaml