#########################################################
# Below all fixed settings for doorbell PCB
#########################################################
substitutions:
  devicename: meek-doorbell
  friendly: Doorbell
  ip: 192.168.100.211
  neopixel: GPIO02 # (D4)
  gpio_relay4: GPIO13 # (D7)

#########################################################
# Everything below can be copy/paste without problem
#########################################################
packages:
  wifi: !include defaults/wifi.yaml
  device_base: !include defaults/for_all_devices.yaml

esphome:
  name: ${devicename}
  on_boot:
    priority: 600
    then:
      - lambda: WiFi.setPhyMode(WIFI_PHY_MODE_11G); 
  
# WIFI_PHY_MODE_11B: 802.11b mode, WIFI_PHY_MODE_11G: 802.11g mode, WIFI_PHY_MODE_11N: 802.11n mode

esp8266:
  board: esp01_1m
  restore_from_flash: true

light:
  - platform: neopixelbus
    default_transition_length: 0s
    type: GRB
    variant: 800KBPS
    pin: ${neopixel}
    num_leds: 1
    name: "${friendly} - Neopixel"
    restore_mode: RESTORE_DEFAULT_OFF
    id: neopixel

binary_sensor:
  - platform: gpio
    pin:
      number: ${gpio_relay4}
      inverted: true
    name: "${friendly} - Doorbell"