#########################################################
# Below all fixed settings for bathroom PCB
#########################################################
substitutions:
  devicename: meek-bathroom
  friendly: Bathroom
  ip: 192.168.100.202
  neopixel: GPIO02 # (D4)
  touch_power: GPIO16 # (D0)
  gpio_touch1: GPIO12 # (D5)
  gpio_relay1: GPIO05 # (D1)
  gpio_relay2: GPIO4 # (D2)
  gpio_relay3: GPIO15 # (D8)

#########################################################
# Everything below can be copy/paste without problem
#########################################################
packages:
  wifi: !include include/wifi.yaml
  device_base: !include include/device_base.yaml

light: !include include/light_one.yaml
switch: !include include/switch_one.yaml
binary_sensor: !include include/binary_sensor_one.yaml