#########################################################
# Below all fixed settings for livingroom PCB
#########################################################
substitutions:
  devicename: meek-livingroom
  friendly: Livingroom
  friendly_switch_1: Wall
  friendly_switch_2: Window
  ip: 192.168.100.201
  neopixel: GPIO02
  touch_power: GPIO16 # (D0)
  gpio_touch1: GPIO13 # (D7)
  gpio_touch2: GPIO14 # (D5)
  gpio_relay1: GPIO05 # (D1)
  
#########################################################
# Everything below can be copy/paste without problem
#########################################################
esphome:
  name: ${devicename}
  on_boot:
    priority: 600
    then:
      - switch.turn_on: touch_power

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  fast_connect: true
  manual_ip:
    static_ip: ${ip}
    gateway: 192.168.100.1
    subnet: 255.255.255.0
    dns1: 192.168.100.1
  ap:
    ssid: ${devicename}
    password: !secret password
    channel: 4

api:
  encryption:
    key: !secret api_key
  reboot_timeout: 15min

time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

web_server:
  port: 80
  
preferences:
  flash_write_interval: 1min
  
logger:
  level: INFO
  
ota:
  safe_mode: true
  password: !secret password

button:
  - platform: factory_reset
    name: "${friendly} - Reset"

sensor:
  - platform: wifi_signal
    name: "${friendly} - Wifi Signal"
    update_interval: 5min

  - platform: uptime
    name: "${friendly} - Uptime"
    update_interval: 5min

light:
  - platform: neopixelbus
    default_transition_length: 0s
    type: GRB
    variant: 800KBPS
    pin: ${neopixel}
    num_leds: 2
    name: "${friendly} - Neopixel All"
    restore_mode: RESTORE_DEFAULT_OFF
    id: neopixel
    effects:
      - strobe:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_flicker:
      - pulse:
          name: "Slow Pulse"
          update_interval: 1s

  - platform: partition
    name: "${friendly_switch_1} - neopixel"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s
    id: neopixel2
    segments:
      - id: neopixel
        from: 1
        to: 1
    effects:
      - strobe:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_flicker:

  - platform: partition
    name: "${friendly_switch_2} - neopixel"
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s
    id: neopixel1
    segments:
      - id: neopixel
        from: 0
        to: 0
    effects:
      - strobe:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_flicker:

switch:
  - platform: gpio
    pin: ${touch_power}
    name: "${friendly} - Touch 1 power"
    icon: mdi:electric-switch
    id: touch_power

  - platform: safe_mode
    name: "${friendly} - Safe Mode"

  - platform: template
    name: "${friendly_switch_1} - Light Switch"
    restore_mode: RESTORE_DEFAULT_OFF
    id: switch1
    optimistic: true
    icon: mdi:nintendo-switch

  - platform: template
    name: "${friendly_switch_1} - Switch longpress"
    restore_mode: RESTORE_DEFAULT_OFF
    id: switch_longpress1
    optimistic: true
    icon: mdi:nintendo-switch

  - platform: template
    name: "${friendly_switch_2} - Light Switch"
    restore_mode: RESTORE_DEFAULT_OFF
    id: switch2
    optimistic: true
    icon: mdi:nintendo-switch

  - platform: template
    name: "${friendly_switch_2} - Switch longpress"
    restore_mode: RESTORE_DEFAULT_OFF
    id: switch_longpress2
    optimistic: true
    icon: mdi:nintendo-switch

  # - platform: gpio
  #   pin: ${gpio_relay1}
  #   name: "${friendly_switch_1} - relay"
  #   icon: mdi:electric-switch

binary_sensor:
  - platform: gpio
    pin: ${gpio_touch1}
    name: "${friendly_switch_1} - Touch"
    icon: mdi:gesture-tap-button
    on_click:
      - min_length: 10ms
        max_length: 500ms
        then:
          - switch.toggle: switch1
      - min_length: 1000ms
        max_length: 2000ms
        then:
          - switch.toggle: switch_longpress1

  - platform: gpio
    pin: ${gpio_touch2}
    name: "${friendly_switch_2} - Touch"
    icon: mdi:gesture-tap-button
    on_click:
      - min_length: 10ms
        max_length: 500ms
        then:
          - switch.toggle: switch2
      - min_length: 1000ms
        max_length: 2000ms
        then:
          - switch.toggle: switch_longpress2

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly} - ip"
      icon: mdi:lan
    ssid:
      name: "${friendly} - ssid"
      icon: mdi:lan
    bssid:
      name: "${friendly} - bssid"
      icon: mdi:lan
    mac_address:
      name: "${friendly} - mac"
      icon: mdi:lan

  - platform: version
    name: "${friendly} - Version"
    hide_timestamp: true