#########################################################
# Below all fixed settings for livingroom PCB
#########################################################
substitutions:
  devicename: meek-livingroom
  friendly: Livingroom
  friendly_switch_1: Wall
  friendly_switch_2: Window
  ip: 192.168.100.201
  neopixel: GPIO02
  touch_power: GPIO16 # (D0)
  gpio_touch1: GPIO14 #GPIO13 # (D7)
  gpio_touch2: GPIO13 #GPIO14 # (D5)
  gpio_relay1: GPIO05 # (D1)
  gpio_relay2: GPIO4 # (D2)
  
#########################################################
# Everything below can be copy/paste without problem
#########################################################
packages:
  wifi: !include include/wifi.yaml
  device_base: !include include/device_base.yaml

light: !include include/light_two.yaml
switch: !include include/switch_two.yaml
binary_sensor: !include include/binary_sensor_two.yaml