#########################################################
# Below all fixed settings for kitchen PCB
#########################################################
substitutions:
  devicename: meek-kitchen
  friendly: Kitchen
  friendly_switch_1: Ceiling
  friendly_switch_2: Cooking
  friendly_switch_3: Sink
  ip: 192.168.100.206
  touch_power: GPIO16 # (D0)
  neopixel: GPIO02 #(D4)
  gpio_touch1: GPIO14 # (D5)
  gpio_touch2: GPIO12 # (D6)
  gpio_touch3: GPIO13 # (D7)
  gpio_relay1: GPIO05 # (D1)
  gpio_relay2: GPIO4 # (D2)
  gpio_relay3: GPIO15 # (D8)

#########################################################
# Everything below can be copy/paste without problem
#########################################################
packages:
  wifi: !include include/wifi.yaml
  device_base: !include include/device_base.yaml

light: !include include/light_three.yaml
switch: !include include/switch_three.yaml
binary_sensor: !include include/binary_sensor_three.yaml