#########################################################
# Below all fixed settings for hallway PCB
#########################################################
substitutions:
  devicename: meek-uat
  friendly: UAT
  ip: 192.168.100.200
  # neopixel: GPIO02 # (D4)
  # touch_power: GPIO16 # (D0)
  # gpio_touch1: GPIO12 # GPIO13 # (D7) ?? MUST BE GPIO12 ??
  # gpio_relay1: GPIO05 # (D1)
  # gpio_relay2: GPIO4 # (D2)
  # gpio_relay3: GPIO15 # (D8)

#########################################################
# Everything below can be copy/paste without problem
#########################################################
esphome:
  name: ${devicename}
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m
  restore_from_flash: true

mdns:
  disabled: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # reboot_timeout: 10s
  # fast_connect: false
  # output_power: 20.0
  # power_save_mode: none