
###########################################################################################
# Control Somfy Shaders
###########################################################################################
- id: "6cda4fe8-102a-43d1-b1b4-8137fce09132"
  alias: "Somfy - Shaders"
  mode: restart
  triggers:
    - trigger: state
      entity_id: 
        - input_boolean.helpers_somfy_blinds

  conditions: []

  variables:
    delay_time: >-
      {% set position = state_attr('cover.balcony', 'current_position') | float(0) %}
      {% if position >= 75 and position <= 100 %} 8
      {% elif position >= 50 and position < 75 %} 16
      {% elif position >= 25 and position < 50 %} 24
      {% elif position >= 0 and position < 25 %} 30
      {% endif %}

    balcony: >-
      {% set maand = now().month %}
      {% if maand in [1, 2, 3] %} 25
      {% elif maand in [4, 5, 6] %} 50
      {% elif maand in [7, 8, 9] %} 75
      {% elif maand in [10, 11, 12] %} 90
      {% endif %}

    livingroom: >-
      {% set maand = now().month %}
      {% if maand in [1, 2, 3] %} 25
      {% elif maand in [4, 5, 6] %} 50
      {% elif maand in [7, 8, 9] %} 75
      {% elif maand in [10, 11, 12] %} 90
      {% endif %}
  
  actions:
    - if:
        - "{{ (trigger.to_state.state == 'on') }}"
      then:
        - action: cover.set_cover_position
          target:
            entity_id: cover.balcony
          data:
            position: "{{ balcony }}"

        - delay: 
            seconds: "{{ delay_time }}"

        - action: cover.set_cover_position
          target:
            entity_id: cover.livingroom
          data:
            position: "{{ livingroom }}"

      else:
        - action: cover.set_cover_position
          target:
            entity_id: cover.balcony
          data:
            position: 100

        - delay: 
            seconds: "{{ delay_time }}"

        - action: cover.set_cover_position
          target:
            entity_id: cover.livingroom
          data:
            position: 100