#  ██████╗ ███████╗███████╗███████╗████████╗    ███████╗███████╗██████╗ ██╗  ██╗ ██████╗ ███╗   ███╗███████╗    ████████╗ ██████╗ ██╗   ██╗ ██████╗██╗  ██╗
#  ██╔══██╗██╔════╝██╔════╝██╔════╝╚══██╔══╝    ██╔════╝██╔════╝██╔══██╗██║  ██║██╔═══██╗████╗ ████║██╔════╝    ╚══██╔══╝██╔═══██╗██║   ██║██╔════╝██║  ██║
#  ██████╔╝█████╗  ███████╗█████╗     ██║       █████╗  ███████╗██████╔╝███████║██║   ██║██╔████╔██║█████╗         ██║   ██║   ██║██║   ██║██║     ███████║
#  ██╔══██╗██╔══╝  ╚════██║██╔══╝     ██║       ██╔══╝  ╚════██║██╔═══╝ ██╔══██║██║   ██║██║╚██╔╝██║██╔══╝         ██║   ██║   ██║██║   ██║██║     ██╔══██║
#  ██║  ██║███████╗███████║███████╗   ██║       ███████╗███████║██║     ██║  ██║╚██████╔╝██║ ╚═╝ ██║███████╗       ██║   ╚██████╔╝╚██████╔╝╚██████╗██║  ██║
#  ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝   ╚═╝       ╚══════╝╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝       ╚═╝    ╚═════╝  ╚═════╝  ╚═════╝╚═╝  ╚═╝
###########################################################################################
# Reset ESPHome Touch by turn off and on the power of it.
###########################################################################################
- id: "91c10b70-3ae3-4999-b28a-cfdf7e9e143a"
  alias: "System - Reset touch of keep on"

  trigger:
    - platform: state
      entity_id:
        - binary_sensor.balcony_touch
        - binary_sensor.bathroom_touch
        - binary_sensor.bedroom_touch
        - binary_sensor.cooking_touch
        - binary_sensor.diningtable_touch
        - binary_sensor.dressoir_touch
        - binary_sensor.hallway_touch
        - binary_sensor.seeling_touch
        - binary_sensor.sink_touch
        - binary_sensor.toilet_touch
        - binary_sensor.wall_touch
        - binary_sensor.window_touch
      to: "on"
      for: "00:00:15"

  variables:
    name: "{{ trigger.entity_id[22:-8] }}"

  action:
    - service: switch.turn_off
      target:
        entity_id: >-
          {% if is_state('binary_sensor.balcony_touch', 'on') %} 
            switch.diningroom_touch_1_power
          {% elif is_state('binary_sensor.bathroom_touch', 'on') %} 
            switch.bathroom_touch_1_power
          {% elif is_state('binary_sensor.bedroom_touch', 'on') %} 
            switch.bedroom_touch_1_power
          {% elif is_state('binary_sensor.cooking_touch', 'on') %}
            switch.kitchen_touch_1_power
          {% elif is_state('binary_sensor.diningtable_touch', 'on') %}
            switch.diningtable_touch_1_power
          {% elif is_state('binary_sensor.dressoir_touch', 'on') %}
            switch.diningroom_touch_1_power
          {% elif is_state('binary_sensor.hallway_touch', 'on') %}
            switch.hallway_touch_1_power
          {% elif is_state('binary_sensor.seeling_touch', 'on') %}
            switch.kitchen_touch_1_power
          {% elif is_state('binary_sensor.sink_touch', 'on') %}
            switch.kitchen_touch_1_power
          {% elif is_state('binary_sensor.toilet_touch', 'on') %}
            switch.toilet_touch_1_power
          {% elif is_state('binary_sensor.wall_touch', 'on') %}
            switch.livingroom_touch_1_power
          {% elif is_state('binary_sensor.window_touch', 'on') %}
            switch.livingroom_touch_1_power
          {% endif %}

    - delay: "00:00:02"

    - service: switch.turn_on
      target:
        entity_id: >-
          {% if is_state('binary_sensor.balcony_touch', 'on') %} 
            switch.diningroom_touch_1_power
          {% elif is_state('binary_sensor.bathroom_touch', 'on') %} 
            switch.bathroom_touch_1_power
          {% elif is_state('binary_sensor.bedroom_touch', 'on') %} 
            switch.bedroom_touch_1_power
          {% elif is_state('binary_sensor.cooking_touch', 'on') %}
            switch.kitchen_touch_1_power
          {% elif is_state('binary_sensor.diningtable_touch', 'on') %}
            switch.diningtable_touch_1_power
          {% elif is_state('binary_sensor.dressoir_touch', 'on') %}
            switch.diningroom_touch_1_power
          {% elif is_state('binary_sensor.hallway_touch', 'on') %}
            switch.hallway_touch_1_power
          {% elif is_state('binary_sensor.seeling_touch', 'on') %}
            switch.kitchen_touch_1_power
          {% elif is_state('binary_sensor.sink_touch', 'on') %}
            switch.kitchen_touch_1_power
          {% elif is_state('binary_sensor.toilet_touch', 'on') %}
            switch.toilet_touch_1_power
          {% elif is_state('binary_sensor.wall_touch', 'on') %}
            switch.livingroom_touch_1_power
          {% elif is_state('binary_sensor.window_touch', 'on') %}
            switch.livingroom_touch_1_power
          {% endif %}

    - service: persistent_notification.create
      data:
        title: "HA - Notification"
        message: |
          The {{ name }} touch was on for 15 seconds. 
          Did a reset on the {{ name }} touch power switch.
        notification_id: "esp_touch_keeps_on"

    - service: script.mobile_notify_no_actionable
      data:
        title: "HA - Notification"
        message: |
          The {{ name }} touch was on for 15 seconds. 
          Did a reset on the {{ name }} touch power switch.
        notification_id: "esp_touch_keeps_on"